<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestTest"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="30,467">
  <properties />
            <testcase name="testSignInSuccess" time="30,466" classname="test.java.TestHboSignIn">
                <failure type="java.lang.Throwable"
                  message="Multiple failures (1)
(1)java.lang.AssertionError:expected [false] but found [true]

Failure 1 of 1
java.lang.AssertionError: expected [false] but found [true]"
              >
<![CDATA[java.lang.Throwable: Multiple failures (1)
(1)java.lang.AssertionError:expected [false] but found [true]

Failure 1 of 1
java.lang.AssertionError: expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertFalse(Assert.java:63)
  org.testng.Assert.assertFalse(Assert.java:73)
  main.TestBase.assertFalse(TestBase.java:69)
  main.TestBase.verifyFalse(TestBase.java:136)
  pageObjects.HboSignIn.isNewDevice(HboSignIn.java:81)
  pageObjects.HboSignIn.enterNewDevice(HboSignIn.java:86)
  test.java.TestHboSignIn.testSignInSuccess(TestHboSignIn.java:60)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:483)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
            <testcase name="testPlayerSuccess" time="0.0" classname="test.java.TestHboSignIn">
          <skipped />
    </testcase>
  
  
</testsuite>
